name: flutter_graph_draw
description: A new Flutter project.

version: 0.0.1
homepage: https://github.com/dlmauri/flutter_graph_draw
author: maurizio dell'oso <dellosomaurizio@gmail.com>

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  geometry_kp: ^0.0.1

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
